### ISSUE TITLE
Login Credentials

### ISSUE THREAD

**Issue by maede97** [hitobito/development#3]
Hi!
I was wondering on how it is possible to get the login credentials for hitobito set up with this repository, because no credentials are posted somewhere.

On the setup side, this works perfectly, thank you very much!

**Comment by psunix** [comment]
Hi!

the password for all seeded test user accounts is "hito42bito". I will update this in the main readme

thx for your feedback, great to here it works !

**Comment by psunix** [comment]
update: passwords of the seeded users is of course set inside the wagons. so the password is depending on the wagon your using.
that's why it does not make sense to add this to this manual

**Comment by maede97** [comment]
Thanks!
Maybe you could add the commands to get the password/set it? (and get the email)

**Comment by carlobeltrame** [comment]
For the record, currently the commands you have to perform to set the root user's password and output login info to the console:
```bash
docker-compose exec rails bash
echo 'p=Person.first; p.update!(password: "hito42bito", first_name: "Puzzle", last_name: "ITC", birthday: "1999-09-09"); "You can now login under http://localhost:3000 as #{p.email} with the password '"'"'hito42bito'"'"'"' | rails c
```
Since the root user is seeded in the core with the email hitobito@puzzle.ch, I have a [PR](github.com/hitobito/hitobito/pull/993) in the core open that will set the password for that user in development to hito42bito.

But beware: The root user account has some known quirks and bugs that we are not fixing because of their low impact. One example is that you cannot visit the OAuth applications page with the root user. You might be better off using the wagon-specific seeded users (see https://github.com/hitobito/hitobito_cevi/blob/master/db/seeds/development/1_people.rb for the CEVI wagon). In particular, the only account that is common to all wagons is `zumkehr at puzzle.ch` / hito42bito.
